---
title: "Figures from: Impacts of host availability and temperature on mosquito-borne parasite transmission"
author: |
    | Kyle J.-M. Dahlin, Suzanne M. O'Regan, Barbara A. Han,
    | John Paul Schmidt, John M. Drake
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    keep_tex: yes
    extra_dependencies: ["float"]
    includes:
      in_header: header.tex
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "doc") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE, warning = FALSE, fig.pos = "H",
  out.extra = ""
)
# Load Libraries----------------------------------------------------------------
library(tidyverse)
library(latex2exp)
library(reshape2)
library(cowplot)
library(viridis)
library(RColorBrewer) # for colorblind friendly color palettes
library(MetBrewer) # for colorblind friendly color palettes
library(cols4all) # for colorblind friendly color palettes
library(here)
library(lemon)
library(see) # for half-violin plots
library(zplyr) #devtools::install_github("burchill/zplyr") from https://github.com/burchill/zplyr/ # only needed for placing text using absolute coordinates in contdact comparison figure

# Plot settings ----

# Set theme
theme_set(theme_minimal(10))

# Helper function: adds a "point at infinity" for plots with infinite sigmaH
inf_skew_func <- function(df, skew, divide, n_rows_to_add) {
  # Get the largest value of log10(sigmaH) in the data frame
  max_log10sigmaH <- filter(df, is.finite(sigmaH)) %>%
    select(sigmaH) %>%
    max() %>%
    log10()
  
  # Define the gap dividing finite and infinite sigmaH
  infinite_divide <- 10^mean(log10(c(divide, skew)))
  
  # Create a proxy sigmaH variable that replaces Inf with the value of "skew"
  df <- mutate(df, sigmaH_proxy = ifelse(is.finite(sigmaH),
                                         sigmaH, skew
  ))
  
  # add more proxy sigmaH values to make a "spread" at Inf
  added_sigma_vals <- seq(divide, skew, length.out = n_rows_to_add)
  for (i in 1:n_rows_to_add) {
    bump_val <- 1 + 0.05 * (i - 1)
    temp <- filter(df, is.infinite(sigmaH)) %>%
      mutate(sigmaH_proxy = ifelse(is.finite(sigmaH), sigmaH,
                                   added_sigma_vals[i]
      ))
    df <- add_row(df, temp) %>% distinct()
  }
  return(df)
}

# Label functions:
appender_sigmaH <- function(string) {
  ifelse(string == "Inf",
         unname(TeX(paste("$\\sigma_H = \\infty$"))),
         unname(TeX(paste("$\\sigma_H = $", string)))
  )
}
appender_KH <- function(string) {
  unname(TeX(paste("$K_H = $", string)))
}

sens_labels <- as_labeller(c(
  "(a) *Ae. aegypti* and DENV" = "(a) *Ae. aegypti* and  \nDENV",
  "(b) *Ae. aegypti* and ZIKV" = "(b) *Ae. aegypti* and   \nZIKV",
  "(c&#41; *Ae. albopictus* and DENV" = "(c&#41; *Ae. albopictus*  \nand DENV",
  "(d) *An. gambiae* and *P. falciparum*" = "(d) *An. gambiae* and  \n*P. falciparum*",
  "(e) *Cx. quinquefasciatus* and WNV" = "(e) *Cx. quinquefasciatus*  \nand  WNV"
))

# Helper function: place legends in empty facets of plot grids
# Code by: Artem Sokolov, found here: https://stackoverflow.com/questions/54438495/shift-legend-into-empty-facets-of-a-faceted-plot-in-ggplot2
shift_legend <- function(p) {
  pnls <- cowplot::plot_to_gtable(p) %>%
    gtable::gtable_filter("panel") %>%
    with(setNames(grobs, layout$name)) %>%
    purrr::keep(~ identical(.x, zeroGrob()))
  
  if (length(pnls) == 0) stop("No empty facets in the plot")
  
  lemon::reposition_legend(p, "center", panel = names(pnls))
}

# Helper function: apply nice labels for pathosystems
pathosystem_labeller <- function(df) {
  df <- df %>%
    ungroup() %>%
    mutate(system_label = case_when(
      system_ID == "Aedes aegypti / DENV" ~ "(a) *Ae. aegypti* and DENV",
      system_ID == "Aedes aegypti / ZIKV" ~ "(b) *Ae. aegypti* and ZIKV",
      system_ID == "Aedes albopictus / DENV" ~ "(c&#41; *Ae. albopictus* and DENV",
      system_ID == "Anopheles gambiae / Plasmodium falciparum" ~ "(d) *An. gambiae* and *P. falciparum*",
      system_ID == "Culex quinquefasciatus / WNV" ~ "(e) *Cx. quinquefasciatus* and WNV"
    ))
  return(df)
}

# Helper function: apply nice labels for focal variables
focalvar_labeller <- function(df) {
  df <- df %>%
    mutate(focal_var = factor(focal_var,
                              levels = c("total", "muV", "sigmaV", "sigmaV_f", "rhoL", "deltaL", "etaV", "betaV"),
                              labels = c(
                                TeX("Overall"),
                                TeX("Adult mortality rate"),
                                TeX("Biting frequency"),
                                TeX("Eggs per female per day"),
                                TeX("Immature development rate"),
                                TeX("Prob. of immature survival"),
                                TeX("Parasite development rate"),
                                TeX("Vector competence")
                              )
    ))
}

# Load required data ----

eps <- .Machine$double.eps

# Vector trait TPC data



# Create data frame of TPCs

data.Vec <- read_rds("results/VecTPC_vals.rds") %>%
  pathosystem_labeller()

# Uncomment this to reduce resolution of trait TPCs, to help with memory issues
# thin_size <- 500
# num_samples <- length(unique(data.Vec$sample_num))
# sample_inds <- sample(1:num_samples, thin_size, replace = FALSE)
# 
# data.Vec <- filter(data.Vec, sample_num %in% sample_inds)

# R0 data
data.R0_TPCs <- read_rds("results/R0_TPC_vals.rds") %>%
  pathosystem_labeller()

data.R0 <- read_rds("results/R0_vals.rds") %>%
  pathosystem_labeller()

# Topt data
data.Topt <- read_rds("results/Topt_vals.rds") %>%
  pathosystem_labeller()

# Critical thermal extrema data
data.CT <- read_rds("results/CT_vals.rds") %>%
  pathosystem_labeller()

# Local sensitivity of R0 to mosquito traits
data.dR0dvar <- read_rds("results/dR0dk_vals.rds") %>%
  ungroup() %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Densities of CTmin/max and Topt
all.density.df <- read_rds("results/CTminmaxTopt_densities.rds") %>%
  ungroup() %>%
  pathosystem_labeller() %>%
  filter(KH > 0.01)

# Uncertainty data for R0
R0.HPD <- read_rds("results/R0_HPD_unc.rds") %>%
  ungroup() %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Uncertainty data for the derivative of R0 wrt temperature
ddTR0.HPD <- read_rds("results/ddTR0_HPD_unc.rds") %>%
  ungroup() %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Uncertainty data for Topt
Topt.HPD <- read_rds("results/Topt_HPD_unc.rds") %>%
  mutate(focal_var = ifelse(focal_var == "lf", "muV", focal_var)) %>% 
  ungroup() %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Uncertainty data for critical thermal extrema
CT.HPD <- read_rds("results/CT_HPD_unc.rds") %>%
  ungroup() %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Derivative of Topt with respect to host pop. density
dToptdKH.HPD <- read_rds("results/dToptdKH_HPD_unc.rds") %>%
  ungroup() %>%
  distinct() %>%
  filter(!is.na(HPD_width)) %>%
  pathosystem_labeller() %>%
  focalvar_labeller()

# Configure data sets for plotting ----

## Get values of vector traits across samples
# Mean values
mean.Vec <- read_rds("results/meanVec_vals.rds")

# Median values (this one is used more frequently)
median.Vec <- read_rds("results/medianVec_vals.rds")

# Compute *mosquito* thermal tolerance range (minimum and maximum)
MosqThermRange_df <- mean.Vec %>%
  pathosystem_labeller() %>%
  group_by(system_label) %>%
  filter(V0 > 0) %>%
  mutate(CTmin_V0 = min(Temperature)) %>%
  mutate(CTmax_V0 = max(Temperature)) %>%
  dplyr::select(system_ID, system_label, CTmin_V0, CTmax_V0) %>%
  distinct()
```

# Figures

```{r fig-1_contact_comparison, dev = c('pdf','svg', 'png'), out.width='100%', fig.align='center', fig.height=5, fig.width=7, fig.align='center', fig.cap='\\label{fig:contact_comparison} A comparison of the Chitnis dynamic contact rate and the standard Ross-Macdonald contact rate models. In the left columns, mosquito population is held constant while in the right columns host population density is held constant. Upper panel: In the Ross-Macdonald model, the mosquito biting rate is constant with respect to both host and mosquito population density (a and b, blue lines) while in the Chitnis model mosquito biting increases with host population density (a, red curve) and decreases with mosquito population density (b, red curve). Lower panels: The relationships between the number of bites that a host receives per day and host and mosquito densities diverge at low host population densities (c) and, to a lesser extent, at high mosquito densities (d). For plots (a) and (c), mosquito population density is fixed at 1000 individuals per km2. For plots (b) and (d), host population density is fixed at 10 individuals per square kilometer. Maximum mosquito biting rate is 0.45 bites per mosquito per day and maximum host biting rate is 100 bites per host per day. Mosquito and host population densities are plotted on a logarithmic scale. '}
# resolution setting
resolution <- 1E2

## Define the contact models
# For each model, there is a vector-to-host and host-to-vector term

# Bites per mosquito per day
vector_host_contact_func <- function(df) {
  with(as.list(df), {
    ret <- case_when(
      # Ross-Macdonald aka Reservoir frequency dependence
      model == "RM" ~ sigma_V,
      # Chitnis dynamic
      model == "CD" ~ sigma_V * sigma_H * H / (sigma_H * H + sigma_V * V)
    )
  })
}

# Bites per host per day
host_vector_contact_func <- function(df) {
  with(as.list(df), {
    ret <- case_when(
      # Ross-Macdonald aka Reservoir frequency dependence
      model == "RM" ~ sigma_V * V / H,
      # Chitnis dynamic
      model == "CD" ~ sigma_H * sigma_V * V / (sigma_H * H + sigma_V * V)
    )
  })
}

## Set up density ranges
host_density_range <- c(1E0, 1E3)
host_fixed_value <- 10
host_density_vec <- sort(c(10^seq(log10(host_density_range[1]),
                                  log10(host_density_range[2]),
                                  length.out = resolution
), host_fixed_value))

vector_density_range <- c(1E0, 1E3)
vector_fixed_value <- 1000
vector_density_vec <- sort(c(10^seq(log10(vector_density_range[1]),
                                    log10(vector_density_range[2]),
                                    length.out = resolution
), vector_fixed_value))

## Set other parameters
max_biting_rate <- 0.45
sigma_V <- max_biting_rate

host_annoyance_threshold <- 100
sigma_H <- host_annoyance_threshold

## Create contact dynamics dataframe
models <- c("RM", "CD")
names(models) <- c("Ross-Macdonald", "Chitnis dynamic")

contact_df <- expand.grid(
  H = host_density_vec,
  V = vector_density_vec,
  sigma_V = sigma_V,
  sigma_H = sigma_H,
  model = models
) %>%
  mutate("Transmission model" = names(model)) %>%
  mutate(bites_mosquito_time = vector_host_contact_func(.)) %>%
  mutate(bites_host_time = host_vector_contact_func(.)) %>%
  rename("Host population density" = H) %>%
  rename("Mosquito population density" = V) %>%
  rename("Bites per mosquito per day" = bites_mosquito_time) %>%
  rename("Bites per host per day" = bites_host_time)

## Put plots together:
new_df <- contact_df %>%
  filter(`Mosquito population density` == vector_fixed_value |
           `Host population density` == host_fixed_value) %>%
  select(-sigma_V, -sigma_H, -model) %>%
  melt(
    id = c(
      "Transmission model", "Bites per mosquito per day",
      "Bites per host per day"
    ),
    value.name = "x_vals"
  ) %>%
  rename(x_vars = variable) %>%
  melt(id = c("Transmission model", "x_vars", "x_vals"), value.name = "y_vals") %>%
  rename(y_vars = variable) %>%
  filter(x_vals != host_fixed_value & x_vals != vector_fixed_value) %>%
  mutate(y_max = 1.05 * y_vals) %>%
  mutate(label = case_when(
    x_vars == "Host population density" & y_vars == "Bites per mosquito per day" ~ "(a)",
    x_vars == "Mosquito population density" & y_vars == "Bites per mosquito per day" ~ "(b)",
    x_vars == "Host population density" & y_vars == "Bites per host per day" ~ "(c)",
    x_vars == "Mosquito population density" & y_vars == "Bites per host per day" ~ "(d)"
  )) %>%
  distinct()

# x = Host population density, y = Bites per mosquito per day
plot_HD_MC <- new_df %>%
  filter(x_vars == "Host population density") %>%
  filter(y_vars == "Bites per mosquito per day") %>%
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
                color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_log10(
    name = "",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "Bites per mosquito per day",
    expand = c(0, 0)
  )

# x = Mosquito population density, y = Bites per mosquito per day
plot_MD_MC <- new_df %>%
  filter(x_vars == "Mosquito population density") %>%
  filter(y_vars == "Bites per mosquito per day") %>%
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
                color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_log10(
    name = "",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "",
    expand = c(0, 0),
    # limits = c(0, NA)
  ) +
  # hide legend
  guides(color = FALSE)

# x = Mosquito population density, y = Bites per host per day
plot_MD_HC <- new_df %>%
  filter(x_vars == "Mosquito population density") %>%
  filter(y_vars == "Bites per host per day") %>%
  # x = density variables, y = contact rates
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
                color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_log10(
    name = "Mosquito population density",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "",
    expand = c(0, 0),
    # limits = c(0, NA)
  )

# x = Host population density, y = Bites per host per day
plot_HD_HC <- new_df %>%
  filter(x_vars == "Host population density") %>%
  filter(y_vars == "Bites per host per day") %>%
  # x = density variables, y = contact rates
  ggplot(aes(x = x_vals, y = y_vals, colour = `Transmission model`)) +
  # curves:
  geom_path(size = 1) +
  geom_blank(aes(y = y_max)) +
  # plot labels
  geom_abs_text(aes(xpos = 0.08, ypos = 0.89, label = label),
                color = "black", show.legend = FALSE
  ) +
  # x-axis:
  scale_x_log10(
    name = "Host population density",
    expand = expansion(mult = c(0, .025))
  ) +
  # y-axis:
  scale_y_continuous(
    name = "Bites per host per day",
    expand = c(0, 0),
    # limits = c(0, NA)
  ) +
  # hide legend
  guides(color = FALSE)

# Combine plots into a grid and remove legends
contact_plot <- plot_grid(
  plot_HD_MC + theme(legend.position = "none"),
  plot_MD_MC + theme(legend.position = "none"),
  plot_HD_HC + theme(legend.position = "none"),
  plot_MD_HC + theme(legend.position = "none")
)

# Set legend to bottom of grid
legend <- get_legend(
  plot_HD_MC +
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# Put together grid and legend
contact_plot <- plot_grid(contact_plot, legend, ncol = 1, rel_heights = c(1, .05))

# Plot
contact_plot
```

```{r fig-3_MosquitoThermalTraits, dev = c('pdf','svg', 'png'),  out.width='100%', fig.height=6, fig.width=9, fig.align='center', fig.cap='\\label{fig:MosquitoThermalTraits} Thermal performance curves (TPCs) for the mosquito and parasite traits used in our model. Curves are shown in color for each of the five systems we considered. Temperatures vary from 10\textdegree C to 35\textdegree C to encompass the full thermal niche of all mosquito species considered in this study (defined as the range of temperatures at which all traits for a given species are positive). Each trait is a unimodal function of temperature except for the lifespan of \\textit{Culex quinquefasciatus} (d). Recruitment rate (a) is derived from a sub-model of immature mosquito population dynamics in equations  (2.6) and (2.7. The \\textit{Aedes aegypti} and DENV and \\textit{Ae. aegypti} and ZIKV recruitment rate (a) and maximum biting frequency (b) curves overlap because infection is assumed to not affect these traits (but see Tesla et al. (2018)). All functions and parameters for generating these curves are derived from Mordecai et al., 2013, 2017, 2019; Tesla et al., 2018; Shocket et al., 2020. Shown here are the median values of the mosquito traits with respect to their TPC hyperparameter posterior distributions. A full description of how these curves were obtained is available in Appendix S2: Section S1.'}
## Set up plot dataframe
MosqThermTraits_df <- median.Vec %>%
  # Mortality rate
  mutate(muV = 1 / lf) %>%
  # Recruitment rate
  mutate(lambdaV = V0 * muV) %>%
  # Prob. of surviving EIP
  mutate(P_EIP = exp(-muV / etaV)) %>%
  # Prob. of larval survival
  # Select relevant traits and parameters
  dplyr::select(Temperature, system_ID, sigmaV, sigmaV_f, rhoL, lf, deltaL, P_EIP, betaV) %>%
  # Turn all columns except Temperature and system_ID into variables
  melt(id = c("Temperature", "system_ID")) %>%
  mutate(variable = factor(variable,
                           levels = c("lf", "sigmaV", "sigmaV_f", "rhoL", "deltaL", "P_EIP", "betaV"),
                           labels = c(
                             TeX("(a) Adult lifespan: $1/\\mu_V$ (days)"),
                             TeX("(b) Biting frequency: $\\sigma_V$ (day$^{-1}$)"),
                             TeX("(c) Eggs per female per day: $\\sigma_V f$"),
                             TeX("(d) Mosquito development rate: $\\rho_L$ (day$^{-1}$)"),
                             TeX("(e) Prob. of immature mosquito survival: $\\delta_L$"),
                             TeX("(f) Probability of surviving EIP: $\\theta_V$"),
                             TeX("(g) Vector competence: $\\beta_V$")
                           )
  )) %>%
  group_by(Temperature, system_ID)

MosqThermTraits_plot <- MosqThermTraits_df %>%
  # Set up plotting variables and theme
  # x = Temperature, y = trait value
  ggplot(mapping = aes(x = Temperature, y = value, group = system_ID)) +
  # Plot trait values:
  geom_line(aes(colour = system_ID), size = 1) +
  # x-axis:
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0),
    limits = c(10, 40),
    breaks = seq(10, 40, 2)
  ) +
  # y-axis:
  scale_y_continuous(expand = c(0.05, 0)) +
  # color:
  scale_color_manual(
    name = "System:",
    values = met.brewer("Egypt", 5, direction = -1),
    labels = function(x) {
      case_when(
        x == "Aedes aegypti / DENV" ~ "*Aedes aegypti* and DENV",
        x == "Aedes aegypti / ZIKV" ~ "*Ae. aegypti* and ZIKV",
        x == "Aedes albopictus / DENV" ~ "*Aedes albopictus* and DENV",
        x == "Anopheles gambiae / Plasmodium falciparum" ~ "*Anopheles gambiae* and *Plasmodium falciparum*",
        x == "Culex quinquefasciatus / WNV" ~ "*Culex quinquefasciatus* and WNV"
      )
    }
  ) +
  # faceting:
  facet_wrap(~variable,
             nrow = 3, scales = "free",
             labeller = labeller(variable = label_parsed)
  ) +
  # legend:
  guides(color = guide_legend(override.aes = list(size = 4))) +
  # theme options:
  theme_minimal_vgrid(10) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(),
    legend.text = ggtext::element_markdown(),
    legend.direction = "vertical",
    legend.justification = "center",
    axis.title.x = element_text(hjust = 0),
    strip.text = element_text(
      face = "bold",
      hjust = 0
    )
  )

shift_legend(MosqThermTraits_plot)
```

```{r fig-4_R0_TPCs, dev = c('pdf','svg', 'png'),  message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:R0_plots} $\\mathcal{R}_0$ as a function of temperature has the usual properties of a thermal performance curve (TPC): it is positive on a single bounded interval and has a unique maximum value. The shape of the $\\mathcal{R}_0$ TPC depends on vertebrate host availability and the mosquito-parasite system. The shape of the thermal response of $\\mathcal{R}_0$ derived from the Ross-Macdonald model (dotted black curves) is independent of vertebrate host population density while those derived from the Chitnis dynamic model are dependent on vertebrate host population density (solid lines in color). Shown here are the median values of $\\mathcal{R}_0$ with respect to the mosquito trait TPC posterior distributions. $\\mathcal{R}_0$ is normalized by dividing by its maximum value in each system, for the given value of biting tolerance and vertebrate host population density. Vertebrate host population density is varied on a log$_{10}$ scale.'}
# Plot R0 vs. temperature curves. One plot for each system
# One curve for Ross-Macdonald, a few for Chitnis

# x-axes = temperature
# y-axes = R0 (normalized so that max(R0) = 1)
# plots = one for each mosquito+pathogen combination, "system_ID"
# curve 1 = Ross-Macdonald R0 (shape doesn't depend on KH)
# curves  = Chitnis dynamic R0,
#   - colour = value of KH. place it on a color scale in the bottom right corner
# newKH_vals <- unique(data.R0$KH)[seq(1, length(unique(data.R0$KH)), length.out = 21)]

data.R0_norm <- data.R0_TPCs %>%
  filter(KH %in% unique(data.R0_TPCs$KH)[seq(1, length(unique(data.R0_TPCs$KH)), length.out = 21)]) %>%
  filter(variable == "R0") %>%
  select(-variable) %>%
  # normalize median of R0 distribution to have a maximum of one
  group_by(system_ID, Model, sigmaH, KH) %>%
  mutate(median_norm = median / max(median)) %>%
  arrange(system_ID, sigmaH, KH, Temperature, median_norm)


R0_plot <- ggplot(mapping = aes(x = Temperature, group = KH)) +
  # path of mean, normalized R0 as a function of temperature (finite sigmaH):
  geom_path(
    data = filter(data.R0_norm, sigmaH == 100),
    aes(y = median_norm, colour = KH, linetype = "finite"),
    lwd = 1
  ) +
  # path of mean, normalized R0 as a function of temperature (infinite sigmaH):
  geom_path(
    data = filter(data.R0_norm, sigmaH == Inf),
    aes(y = median_norm, linetype = "infinite", colour = "black"),
    colour = "black",
    lwd = 1.5
  ) +
  # x-axis:
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0),
    limits = c(14, 34)
  ) +
  # y-axis:
  scale_y_continuous(
    name = TeX("Normalized $R_0$"),
    expand = c(0, .05)
  ) +
  # color: scaled log10, color-blind friendly
  scale_color_viridis(
    name = "Vertebrate host population\ndensity (ind/ha)",
    trans = "log10",
    breaks = 10^seq(-2, 4),
    labels = unname(c(0.01, 0.1, 1, 10, 100, TeX("$10^3$"), TeX("$10^4$"))),
    option = "plasma"
  ) +
  # fill: scaled log10, color-blind friendly
  scale_fill_viridis(
    name = "Vertebrate host population\ndensity (ind/ha)",
    trans = "log10",
    breaks = 10^seq(-2, 4),
    labels = unname(c(0.01, 0.1, 1, 10, 100, TeX("$10^3$"), TeX("$10^4$"))),
    option = "plasma"
  ) +
  # linetype:
  scale_linetype_manual(
    name = "Biting tolerance\n(bites per host per day)",
    breaks = c("finite", "infinite"),
    labels = unname(c(TeX("100 (Chitnis)"), TeX("$\\infty$ (Ross-Macdonald)"))),
    values = c("solid", "22")
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend
  guides(
    color = guide_colourbar(
      title.position = "top",
      nrow = 1,
      barwidth = 12,
      show.limits = TRUE,
      direction = "horizontal"
    ),
    linetype = guide_legend(
      title.position = "top",
      nrow = 2,
      keywidth = 4,
      direction = "vertical"
    )
  ) +
  # theme options:
  theme_minimal_vgrid(10) +
  theme(
    legend.box = "vertical",
    legend.margin = margin(),
    legend.title = element_text(size = 10),
    legend.text = element_text(
      size = 10,
      hjust = 0
    ),
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(R0_plot)
```

```{r fig-5_Topt, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt} The thermal optimum for transmission, $T_{\\mathrm{opt}}$, may be sensitive to vertebrate host population density and biting tolerance. Here, $T_{\\mathrm{opt}}$ is plotted as a function of vertebrate host population density and biting tolerance for each of the five systems. In the Ross-Macdonald model, where biting tolerance is assumed to be infinite, $T_{\\mathrm{opt}}$ is independent of vertebrate host population density (upper bars in plots). But when biting tolerance is limited, $T_{\\mathrm{opt}}$ can vary as much as 5\textdegree C (d). $T_{\\mathrm{opt}}$ may increase (d) or decrease (a, b, c, e) as vertebrate host population density or biting tolerance is increased. Shown here are the median values of $T_{\\mathrm{opt}}$ with respect to the mosquito trait TPC posterior distributions. Both biting tolerance and vertebrate host population density are varied on a $\\log_{10}$ scale. $\\mathcal{R}_0$ is greater than one in the region contained within the black $\\mathcal{R}_0=1$ curve. All remaining parameters are given in Table 1 and Figure 3. '}
# Shows how the transmission thermal optimum depends on vertebrate host availability (density and biting tolerance) in each of the systems we consider.

#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = width of parasite thermal niche (CTmax - CTmin)
# Facets = systems

# Value of sigmaH to replace 'Inf' with for plotting
infinite_skew <- 10^2.35
# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^2.7
Toptalt_df <- data.Topt %>%
  # Arrange along the plotting variables
  arrange(system_ID, sigmaH, KH, median) %>%
  mutate(sigmaH_proxy = sigmaH) %>% 
  filter(sigmaH_proxy < infinite_skew | is.infinite(sigmaH_proxy))

# add many proxy sigmaH points at infinity to make the values easier to see there
max_sigmaH <- max(filter(Toptalt_df, is.finite(sigmaH))$sigmaH)


Toptalt_df <- inf_skew_func(Toptalt_df, infinite_skew, infinite_divide, 8)

# Define sigmaH tick breaks and labels
sigmaH_breaks <- c(10^c(seq(-1, 2, by = 1)), 10^2.3125, 10^2.5625)
sigmaH_labels <- c(paste(c(10^c(seq(-1, 2, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$"))

min_Topt <- floor(min(min(Toptalt_df$mean), min(Toptalt_df$median)))
max_Topt <- ceiling(max(max(Toptalt_df$mean), max(Toptalt_df$median)))
Topt_breaks <- seq(min_Topt, max_Topt, by = 1)

# Plot median of Topt heat map
Toptalt_plots <- Toptalt_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = transmission thermal optimum
  ggplot(aes(x = KH, y = sigmaH_proxy, z = median)) +
  # Topt for FINITE sigmaH:
  geom_contour_filled(
    data = filter(Toptalt_df, sigmaH_proxy < 10^2.2),
    breaks = Topt_breaks
  ) +
  # Topt for INFINITE sigmaH:
  geom_contour_filled(
    data = filter(Toptalt_df, sigmaH_proxy > infinite_skew) %>%
      group_by(system_ID) %>%
      mutate(median = median(median), .groups = "keep"),
    size = 1,
    breaks = Topt_breaks
  ) +
  # # R0 = 1 contour: use where CTwidth = 0 (i.e. where R0<1 at any temperature)
  geom_contour(
    data = filter(data.CT, variable == "CTwidth", sigmaH < infinite_divide),
    aes(y = sigmaH, z = median, colour = "R0 = 1"),
    breaks = min(filter(data.CT, variable == "CTwidth", median > 0)$median),
    size = 1
  ) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.01, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # fill:
  scale_fill_manual(
    name = "Transmission thermal optimum (°C)",
    values = met.brewer("Johnson",
                        n = length(Topt_breaks),
                        direction = -1
    )
  ) +
  # color:
  scale_colour_manual(
    name = "",
    labels = c("R0=1" = unname(TeX("$\\mathcal{R}_0=1$"))),
    values = c("black"),
    guide = guide_legend(
      order = 1,
      keyheight = unit(1, "cm"),
      override.aes = list(size = 6)
    )
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top",
    title.hjust = 0.5,
    barwidth = 12,
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(10) +
  theme(
    legend.box = "vertical",
    legend.position = "right",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(Toptalt_plots)
```

```{r fig-6_CT_Width, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_Width} The parasite population thermal niche, the range of temperatures at which parasite transmission is expected to persist, is widest when biting tolerance is high and vertebrate host population density is low. As vertebrate host population density approaches an upper threshold, the width of the parasite population thermal niche shrinks to zero. At low levels of biting tolerance, there is also a lower threshold to vertebrate host population density. Shown here are the median values of $\\textrm{CT}_{\\textrm{width}}$ with respect to the mosquito trait TPC posterior distributions. Vertebrate host population density and biting tolerance are both plotted on $\\log_{10}$ scales. Biting tolerance is varied from one to one thousand bites per day, with an additional point at infinity to illustrate the case where biting tolerance is unlimited (the Ross-Macdonald model). Both biting tolerance and vertebrate host population density are varied on a $\\log_{10}$ scale. All remaining parameters are given in Table 1 and Figure 3.'}
# Shows how the parasite thermal niche (temperatures between CT_min and CT_max)
# depends on vertebrate host availability (density and biting tolerance) in each
# of the focal systems.

#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = width of parasite thermal niche (CTmax - CTmin)
# Facets = systems

CTwidth_df <- data.CT %>%
  filter(variable == "CTwidth") %>%
  mutate(sigmaH_proxy = sigmaH) %>%
  # Arrange along the plotting variables
  arrange(system_ID, KH, sigmaH_proxy, median) %>%
  ungroup()

CTwidth_df <- inf_skew_func(CTwidth_df, infinite_skew, infinite_divide, 8)

CTWidth_heat_plots <- CTwidth_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = width of parasite thermal median_CTwidth
  ggplot(aes(x = KH, y = sigmaH_proxy, z = median)) +
  # CTwidth for FINITE sigmaH:
  geom_contour_filled(data = filter(CTwidth_df, sigmaH_proxy < 10^2.2)) +
  # CTwidth for INFINITE sigmaH:
  geom_contour_filled(data = filter(
    CTwidth_df,
    sigmaH_proxy > 10^2.4,
    sigmaH_proxy < infinite_divide
  )) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # color:
  scale_fill_viridis_d(
    name = "Parasite thermal tolerance\nrange width (°C)",
    option = "plasma"
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top",
    title.hjust = 0.5,
    barwidth = 12, # unit(5, "cm"),
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(10) +
  theme(
    legend.box = "horizontal",
    legend.position = "bottom",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(CTWidth_heat_plots)
```

```{r fig-7_explain_sensitivity, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:dR0dvar_comp} Comparison of the local sensitivities of $\\mathcal{R}_0$ to mosquito traits across temperatures for two values of $\\sigma_H$. Generally, $\\mathcal{R}_0$ is most sensitive to biting frequency, the probability of surviving the extrinsic incubation period, and vector competence. Shown here are the median values of the derivative of $\\mathcal{R}_0$ with respect to each focal mosquito trait across the mosquito trait TPC hyperparameter posterior distributions. Sensitivity values are shown on a logarithmic scale with solid lines indicating positive values and dotted lines indicating negative. Temperatures are restricted to those at which the median of $\\mathcal{R}_0$ is positive for the given system.'}

KH_vals <- c(1, 100)
sigmaH_val <- 10

data.dR0dT <- data.dR0dvar %>%
  filter((KH %in% KH_vals & sigmaH == sigmaH_val) | (KH == 100 & is.infinite(sigmaH)))

temp_lims <- select(data.R0, system_ID, system_label, Temperature, Model, sigmaH, KH, median_R0 = median) %>%
  filter(KH %in% KH_vals & sigmaH %in% c(sigmaH_val, Inf)) %>%
  filter(!is.na(median_R0), median_R0 > eps) %>%
  group_by(system_ID) %>% 
  summarise(min_Temp = min(Temperature),
            max_Temp = max(Temperature))


val_lims <- tibble(sigmaH = unique(data.dR0dT$sigmaH), 
                   min_median = c(-90, -0.05), 
                   max_median = c(5, 0.5))


dR0dk.df <- data.dR0dT %>%
  filter(
    KH %in% KH_vals,
    sigmaH %in% unique(data.dR0dT$sigmaH)
  ) %>%
  right_join(select(data.R0, system_ID, system_label, Temperature, Model, sigmaH, KH, median_R0 = median) %>%
               filter(KH %in% KH_vals & sigmaH %in% unique(data.dR0dT$sigmaH))) %>%
  # Restrict to relevant temperatures (i.e. where V0 and R0 > 0)
  right_join(temp_lims) %>% 
  group_by(system_ID) %>% 
  filter(Temperature > min_Temp, Temperature < max_Temp) %>% 
  filter(!is.na(median)) %>% 
  ungroup() %>% 
  # Restrict plotted values (so all plots are visible)
  right_join(val_lims) %>% 
  group_by(sigmaH) %>% 
  # filter(median > min_median, median < max_median) %>% 
  ungroup() %>% 
  # filter(median_R0 > 0) %>%
  mutate(abs_median = abs(median)) %>%
  # Normalize values to better tell which is most important
  mutate(sign_median = sign(median)) %>%
  group_by(system_ID, sigmaH, KH) %>%
  mutate(norm_median = ifelse(sign_median>0,
                              sign_median * median / max(median, na.rm = TRUE),
                              sign_median * median / min(median, na.rm = TRUE))) %>%
  filter(sign_median != 0, !is.na(sign_median)) %>%
  arrange(sign_median) %>%
  arrange(Temperature)

comp_dR0dk.df <- dR0dk.df %>%
  # filter(sigmaH == 10) %>% 
  filter(focal_var != "Overall") %>% 
  group_by(system_ID, Temperature, sigmaH, KH) %>% 
  mutate(abs_median = abs(median),
         total_sens = sum(abs_median),
         prop_sens = abs_median / total_sens) %>% 
  arrange(system_label, Temperature, KH, sigmaH, focal_var)

plot.comp_dR0dk <- comp_dR0dk.df %>%
  filter(is.finite(sigmaH)) %>% 
  # filter(focal_var %in% c("Overall")) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = Temperature, y = prop_sens, fill = focal_var, color = focal_var,
  )) +
  # geom_area() +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0, lwd = 0.25) +
  scale_color_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    name = unname(TeX("Contributions to overall local sensitivity of $\\,R_0$")),
    expand = c(0, 0)
  ) +
  facet_rep_grid(
    rows = vars(sigmaH, KH),
    cols = vars(system_label),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed),
      KH = as_labeller(appender_KH, default = label_parsed)
    ),
    scales = "free"
  ) +
  guides(linetype = guide_legend(
    title.position = "left",
    title.vjust = 0.5,
    direction = "vertical"
  )) +
  theme_minimal_hgrid(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    legend.position = "bottom",
    legend.justification = 0.5,
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )


# plot.comp_dR0dk


compzoom_dR0dk.df <- comp_dR0dk.df %>%
  filter(sigmaH == sigmaH_val) %>% 
  select(system_ID, Temperature, sigmaH, KH, focal_var, system_label, prop_sens) %>%
  pivot_wider(names_from = KH, values_from = prop_sens) %>%
  mutate(abs_comp = `100` - `1`)

plot.compzoom_dR0dk <- compzoom_dR0dk.df %>% 
  ggplot(aes(x = Temperature, y = abs_comp, fill = focal_var, color = focal_var,
  )) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0, lwd = 0.25) +
  scale_color_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    name = unname(TeX("Change in contributions to overall local sensitivity of $\\,R_0$ \n  from $\\,K_H = 1$ to $\\,K_H = 100$ ")),
    expand = c(0, 0)
  ) +
  facet_rep_grid(
    # rows = vars(sigmaH),
    cols = vars(system_label),
    labeller = labeller(
      system_label = sens_labels,
      # sigmaH = as_labeller(appender_sigmaH, default = label_parsed),
      # KH = as_labeller(appender_KH, default = label_parsed)
    ),
    scales = "free"
  ) +
  guides(linetype = guide_legend(
    title.position = "left",
    title.vjust = 0.5,
    direction = "vertical"
  )) +
  theme_minimal_hgrid(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    legend.position = "bottom",
    legend.justification = 0.5,
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

plot.compzoom_dR0dk
```
# Supplementary Figures

```{r fig-S0_MosquitoDensity, dev = c('pdf','svg', 'png'),  out.width='100%', fig.height=6, fig.width=9, fig.align='center', fig.cap='\\label{fig:MosquitoThermalTraits} Thermal performance curves (TPCs) for the mosquito and parasite traits used in our model. Curves are shown in color for each of the five systems we considered. Temperatures vary from 10\textdegree C to 35\textdegree C to encompass the full thermal niche of all mosquito species considered in this study (defined as the range of temperatures at which all traits for a given species are positive). Each trait is a unimodal function of temperature except for the lifespan of \\textit{Culex quinquefasciatus} (d). Recruitment rate (a) is derived from a sub-model of immature mosquito population dynamics in equations  (2.6) and (2.7. The \\textit{Aedes aegypti} and DENV and \\textit{Ae. aegypti} and ZIKV recruitment rate (a) and maximum biting frequency (b) curves overlap because infection is assumed to not affect these traits (but see Tesla et al. (2018)). All functions and parameters for generating these curves are derived from Mordecai et al., 2013, 2017, 2019; Tesla et al., 2018; Shocket et al., 2020. Shown here are the median values of the mosquito traits with respect to their TPC hyperparameter posterior distributions. A full description of how these curves were obtained is available in Appendix S2: Section S1.'}
## Set up plot dataframe
MosqThermTraits_df <- median.Vec %>% 
  dplyr::select(Temperature, system_ID, `Mosquito population density` = V0)  %>%
  group_by(Temperature, system_ID)

MosqThermTraits_plot <- MosqThermTraits_df %>%
  # Set up plotting variables and theme
  # x = Temperature, y = trait value
  ggplot(mapping = aes(x = Temperature, y = `Mosquito population density`, group = system_ID)) +
  # Plot trait values:
  geom_line(aes(colour = system_ID), size = 1) +
  # x-axis:
  scale_x_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0),
    limits = c(10, 40),
    breaks = seq(10, 40, 2)
  ) +
  # y-axis:
  scale_y_continuous("Equilibrium adult mosquito population density", 
                     expand = c(0.05, 0)) +
  # color:
  scale_color_manual(
    name = "System:",
    values = met.brewer("Egypt", 5, direction = -1),
    labels = function(x) {
      case_when(
        x == "Aedes aegypti / DENV" ~ "*Aedes aegypti* and DENV",
        x == "Aedes aegypti / ZIKV" ~ "*Ae. aegypti* and ZIKV",
        x == "Aedes albopictus / DENV" ~ "*Aedes albopictus* and DENV",
        x == "Anopheles gambiae / Plasmodium falciparum" ~ "*Anopheles gambiae* and *Plasmodium falciparum*",
        x == "Culex quinquefasciatus / WNV" ~ "*Culex quinquefasciatus* and WNV"
      )
    }
  )  +
  # legend:
  guides(color = guide_legend(override.aes = list(size = 4))) +
  # theme options:
  theme_minimal(10) +
  theme(
    legend.margin = margin(),
    legend.text = ggtext::element_markdown(),
    legend.direction = "vertical",
    legend.justification = "center",
    strip.text = element_text(
      face = "bold",
      hjust = 0
    )
  )

MosqThermTraits_plot
```

```{r fig-S1_R0_heatmap_plots_all, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=11, fig.align='center', fig.cap='\\label{fig:R0_heatmap_plots_all} The transmission thermal optimum, $T_{\\textrm{opt}}$, is a sigmoidal function of vertebrate host population density. The variation in $T_{\\textrm{opt}}$ varies substantially between the five systems, with \\textit{Anopheles} spp. and \\textit{P. falciparum} (d) having an over 5\textdegree C change in $T_{\\textrm{opt}}$ as vertebrate host population density is increased. Note that the thermal optimum can be an increasing (d) or decreasing (a, b, c, e) function of vertebrate host population density. Shown here are the median values of $T_{\\textrm{opt}}$ with respect to mosquito trait TPC hyperparameter posterior distributions. Vertebrate host population density is varied on a $\\log_{10}$ scale. All remaining parameters are given in Table 1 and Figure 3.'}
# Plot R0 vs. temperature and biting tolerance (sigmaH). One panel each for low, mid, high vert host pop density.

# x = vertebrate host biting tolerance (needs to vary from "zero" to "infinity")
# y = Temperature
# color = R0
# curves:
#   R0 = 1 contour (black curve)
#   Topt (red curve)

# Facets:
# Rows = levels of vertebrate host population density
# Columns = two MBPT systems
# Total = 6 plots

## Set up plot data frame
# We re-create the output data frame so that we can vary sigmaH correctly.
# We also drop the resolution of KH down to just three values
# Need to update functions so that sigmaH == Inf <~> Model == "Ross-Macdonald"

## Configure data frame for plotting
R0_df <- data.R0 %>%
  select(system_ID, system_label, Temperature, sigmaH, KH, median, mean) %>%
  rename(R0 = mean) %>%
  # Consider only 3 values of KH (on a log10-scale)
  filter(KH %in% c(.1, 1, 10)) %>%
  # Choose a limited range of sigmaH values
  filter(sigmaH < 10^2.275 | is.infinite(sigmaH)) %>%
  # Group by plotting variables
  group_by(system_ID, KH, sigmaH) %>%
  # Calculate Topt (which.max requires grouping)
  mutate(Topt = `Temperature`[which.max(R0)]) %>%
  as_tibble() %>%
  arrange(system_ID, sigmaH, Temperature)

## Add a "point at infinity" for sigmaH
# Value of sigmaH to replace 'Inf' with for plotting
infinite_skew <- 10^2.75

# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^2.4

R0_df <- inf_skew_func(R0_df, infinite_skew, infinite_divide, 8)

Topt_for_R0_df <- data.Topt %>%
  # Arrange along the plotting variables
  arrange(system_ID, sigmaH, KH, median) %>%
  mutate(sigmaH_proxy = sigmaH)
Topt_for_R0_df <- inf_skew_func(Topt_for_R0_df, infinite_skew, infinite_divide, 8)


## PLOTTING ##

## Options
# Define sigmaH tick breaks and labels
sigmaH_breaks_heatmap <- c(10^c(seq(-1, 2, by = 1)), infinite_divide, infinite_skew)
sigmaH_labels_heatmap <- c(paste(c(10^c(seq(-1, 2, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$"))

# Labels for facet rows
R0_df$KH <- factor(R0_df$KH, levels = c(.1, 1, 10))
mylabels <- as_labeller(c(
  `0.1` = "0.1 vertebrate hosts / ha",
  `1` = "1 vertebrate host / ha",
  `10` = "10 vertebrate hosts / ha"
))

R0_heatmap_labels <- as_labeller(c(
  "(a) *Ae. aegypti* and DENV" = "(a) *Ae. aegypti*  \nand  DENV",
  "(b) *Ae. aegypti* and ZIKV" = "(b) *Ae. aegypti*  \nand  ZIKV",
  "(c&#41; *Ae. albopictus* and DENV" = "(c&#41; *Ae. albopictus*  \nand  DENV",
  "(d) *An. gambiae* and *P. falciparum*" = "(d) *An. gambiae*  \nand  *P. falciparum*",
  "(e) *Cx. quinquefasciatus* and WNV" = "(e) *Cx. quinquefasciatus*  \nand  WNV"
))

# Breaks used to decide fill for the heat map
fill_breaks <- c(1, seq(5, 20, by = 5), Inf)

# Define colors for heat map so that values of R0>1 go from yellow to red
my.cols <- rev(c(rev(brewer.pal(length(fill_breaks) - 1, "YlOrRd"))))

## PLOT ##
R0_plot <- R0_df %>%
  ggplot(mapping = aes(x = sigmaH_proxy, y = Temperature)) +
  # Mosquito thermal tolerance range lines
  geom_hline(
    data = MosqThermRange_df,
    aes(yintercept = CTmin_V0, colour = "VTTR"),
    lwd = 1.275
  ) +
  geom_hline(
    data = MosqThermRange_df,
    aes(yintercept = CTmax_V0, colour = "VTTR"),
    lwd = 1.275
  ) +
  # R0 contours for FINITE sigmaH:
  geom_contour_filled(
    data = filter(R0_df, sigmaH_proxy < infinite_divide**0.98),
    mapping = aes(z = R0),
    breaks = fill_breaks
  ) +
  # R0 contours for INFINITE sigmaH:
  geom_contour_filled(
    data = filter(R0_df, sigmaH_proxy > infinite_divide**1.02),
    mapping = aes(z = R0),
    breaks = fill_breaks
  ) +
  # R0 = 1 contour:
  geom_contour(aes(colour = "R0=1", z = R0), breaks = c(1), size = 1) +
  # Topt curve:
  geom_path(
    data = filter(Topt_for_R0_df, KH %in% c(.1, 1, 10)) %>% arrange(sigmaH_proxy),
    mapping = aes(
      x = sigmaH_proxy,
      y = median,
      colour = "Topt"
    ),
    lwd = 1,
    linetype = 1
  ) +
  # white lines breaking up finite/infinite sigmaH values
  geom_vline(
    aes(xintercept = 0.85 * infinite_divide),
    colour = "white",
    lwd = .8,
    show.legend = FALSE
  ) +
  geom_vline(
    aes(xintercept = infinite_divide),
    colour = "white",
    lwd = .8,
    show.legend = FALSE
  ) +
  geom_vline(
    aes(xintercept = 1.2 * infinite_divide),
    colour = "white",
    lwd = .8,
    show.legend = FALSE
  ) +
  # x-axis:
  scale_x_log10(
    name = TeX("Vertebrate host biting tolerance (bites per host per day)"),
    breaks = sigmaH_breaks_heatmap,
    labels = sigmaH_labels_heatmap,
    expand = c(0, 0)
  ) +
  # y-axis:
  scale_y_continuous(
    name = expression("Temperature "(degree * C)),
    expand = c(0, 0),
    limits = c(16, 35),
    breaks = seq(10, 36, by = 2)
  ) +
  # color:
  scale_colour_manual(
    name = "",
    labels = c(
      "R0=1" = unname(TeX("$R_0=1$")),
      "Topt" = "Transmission\nthermal\noptimum",
      "VTTR" = "Mosquito\npopulation\nthermal\nniche"
    ),
    values = c("black", "purple", "grey"),
    guide = guide_legend(
      order = 1,
      keyheight = unit(2, "cm"),
      override.aes = list(size = 6)
    )
  ) +
  # fill:
  scale_fill_manual(
    name = TeX("$R_0$"),
    values = my.cols,
    guide = guide_colorsteps(
      order = 2,
      breaks = fill_breaks,
      barheight = unit(8, "cm")
    )
  ) +
  # faceting:
  facet_grid(
    rows = vars(KH),
    cols = vars(system_label),
    labeller = labeller(
      .rows = mylabels,
      .cols = R0_heatmap_labels
    ),
    # repeat.tick.labels = "left"
  ) +
  # theme options:
  theme_minimal_hgrid(10) +
  theme(
    axis.line = element_line(),
    legend.text = element_text(size = 10),
    legend.text.align = 0,
    strip.text.y = ggtext::element_markdown(
      size = 7,
      hjust = 0.5
    ),
    strip.text.x = ggtext::element_markdown(
      size = 7,
      hjust = 0
    ),
    panel.spacing = unit(2, "pt")
  )

# Plot it
R0_plot
```

```{r fig-S2_Topt_plots_varyKH, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_plots_varyKH} The transmission thermal optimum, $T_{\\textrm{opt}}$, is a sigmoidal function of vertebrate host population density. The variation in $T_{\\textrm{opt}}$ varies substantially between the five systems, with \\textit{Anopheles} spp. and \\textit{P. falciparum} (d) having an over 5\textdegree C change in $T_{\\textrm{opt}}$ as vertebrate host population density is increased. Note that the thermal optimum can be an increasing (d) or decreasing (a, b, c, e) function of vertebrate host population density. Shown here are the median values of $T_{\\textrm{opt}}$ with respect to mosquito trait TPC hyperparameter posterior distributions. Vertebrate host population density is varied on a $\\log_{10}$ scale. All remaining parameters are given in Table 1 and Figure 3.'}
Topt_df <- data.Topt %>%
  filter(KH < 10^4 + 1) %>%
  pivot_wider(
    id_cols = c("system_label", "Model", "sigmaH", "KH"),
    names_from = variable,
    values_from = c("mean", "median", "lowHCI", "highHCI")
  ) %>%
  rename(
    mean = mean_Topt, median = median_Topt, lowHCI = lowHCI_Topt,
    highHCI = highHCI_Topt
  ) %>%
  # Arrange along the plotting variables
  arrange(system_label, KH, median, sigmaH) %>%
  ungroup()

# PLOTTING
Topt_plot <- Topt_df %>%
  filter(sigmaH %in% c(1, 10, 100, Inf)) %>%
  ## Set up plot ##
  # color = sigmaH
  ggplot(aes(x = KH, colour = as.factor(sigmaH))) +
  # Topt curves:
  geom_path(aes(y = median), lwd = 1) +
  # x-axis: log10 scale, no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    breaks = c(10^c(seq(-1, 4, by = 1))),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis
  scale_y_continuous(
    name = expression("Thermal optimum "(degree * C)),
    expand = c(0, 0),
    limits = c(21, 30.5),
    breaks = seq(21, 32, by = 1)
  ) +
  # color:
  scale_colour_manual(
    name = "Vertebrate host biting tolerance\n(bites per host per day)",
    values = c(met.brewer("VanGogh3", 4, direction = 1), "black"),
    breaks = c(1, 10, 100, Inf),
    labels = unname(c("1 (Chitnis)", "10 (Chitnis)", "100 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)")))
  ) +
  scale_fill_manual(
    name = "Vertebrate host biting tolerance\n(bites per host per day)",
    values = c(met.brewer("VanGogh3", 4, direction = 1), "black"),
    breaks = c(1, 10, 100, Inf),
    labels = unname(c("1 (Chitnis)", "10 (Chitnis)", "100 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)")))
  ) +
  # faceting:
  facet_wrap(~system_label, nrow = 2, labeller = labeller()) +
  # theme options:
  theme_minimal(10) +
  guides(color = guide_legend(override.aes = list(size = 4))) +
  theme(
    legend.position = "bottom",
    legend.margin = margin(),
    legend.direction = "vertical",
    legend.title = element_text(size = 10),
    legend.text = element_text(
      size = 10,
      hjust = 0
    ),
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )


# Plot
shift_legend(Topt_plot)
```

```{r fig-S3_Topt_plots_varysigmaH, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_plots} The thermal optima predicted by the model can be substantially different at low levels of biting tolerance. At low host population densities, there may be warmer (a, b, c, e) or cooler (d) thermal optima when biting tolerance is low compared to when it is high. Shown here are the median values of $T_{\\textrm{opt}}$ with respect to mosquito trait TPC hyperparameter posterior distributions. Vertebrate host biting tolerance is varied on a $\\log_{10}$ scale with a break to indicate values of $\\mathcal{R}_0$ when biting tolerance is unlimited. '}
# x-axis = vertebrate host biting tolerance
# y-axis = thermal optimum
# color = vertebrate host population density

infinite_skew <- 10^3.7
# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^3.35 # 10^log10(max_sigmaH*1)

Topt_df <- data.Topt %>%
  mutate(sigmaH_proxy = ifelse(is.finite(sigmaH),
                               sigmaH,
                               infinite_skew
  ))
Topt_df <- inf_skew_func(Topt_df, infinite_skew, infinite_divide, 6)

sigmaH_breaks <- c(10^c(seq(-1, 3, by = 1)), 1.15 * infinite_divide, infinite_skew)
sigmaH_labels <- c(TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$")), TeX("$\\ldots$"), TeX("$\\infty$"))

Topt_plot <- Topt_df %>%
  # Choose appropriate pop. dens. values and group
  filter(KH %in% 10^seq(0, 3)) %>%
  arrange(system_label, KH, sigmaH, median) %>%
  ## Set up plot ##
  # color = sigmaH
  ggplot(aes(x = sigmaH_proxy, colour = as.factor(KH))) +
  # Topt curves:
  geom_path(aes(y = median), lwd = 1) +
  # white lines breaking up finite/infinite sigmaH values:
  geom_vline(
    aes(xintercept = 1.05 * infinite_divide),
    colour = "white",
    lwd = .9,
    show.legend = FALSE
  ) +
  geom_vline(
    aes(xintercept = 1.15 * infinite_divide),
    colour = "white",
    lwd = .9,
    show.legend = FALSE
  ) +
  geom_vline(
    aes(xintercept = 1.25 * infinite_divide),
    colour = "white",
    lwd = .9,
    show.legend = FALSE
  ) +
  # x-axis: Use a log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    # limits = c(0.5, 150),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # y-axis
  scale_y_continuous(
    name = expression("Thermal optimum "(degree * C)),
    expand = c(0, 0), # c(0.05, 0.05),
    limits = c(21, 30), # mean: 21-31, median: 21-32
    breaks = seq(21, 32, by = 1)
  ) +
  # color:
  scale_colour_manual(
    name = "Vertebrate host population\ndensity (ind/ha)",
    values = met.brewer("Hokusai3", 4)
  ) +
  scale_fill_manual(
    name = "Vertebrate host population\ndensity (ind/ha)",
    values = met.brewer("Hokusai3", 4)
  ) +
  # faceting:
  facet_wrap(~system_label,
             scales = "free",
             nrow = 2,
             labeller = labeller()
  ) +
  # theme options:
  theme_minimal(10) +
  guides(color = guide_legend(override.aes = list(size = 4))) +
  theme(
    legend.position = "bottom",
    legend.margin = margin(),
    legend.direction = "vertical",
    legend.title = element_text(size = 10),
    legend.text = element_text(
      size = 10,
      hjust = 0
    ),
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(Topt_plot)
```


```{r fig-S4_CTmin, dev = c('pdf','svg', 'png'), dev="cairo_pdf", message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmin} The critical thermal minimum for parasite population persistence as a function of vertebrate host population density and biting tolerance. Grey areas indicate combinations of vertebrate host population density and biting tolerance in which the parasite population is expected to not persist at any temperature. In the region where vertebrate host population density and biting tolerance are both less than 10, critical thermal minima and maxima are very similar (see Figure 6 in the main text). Shown here are the median values of the critical thermal minimum with respect to mosquito trait TPC hyperparameter posterior distributions. Both vertebrate host population density and biting tolerance are varied on a $\\log_{10}$ scale with a break in biting tolerance values to indicate when biting tolerance is unlimited. '}
#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = parasite critical thermal minimum (CTmin)
# Facets = systems

# add many proxy sigmaH points at infinity to make the values easier to see there
max_sigmaH <- max(filter(data.CT, is.finite(sigmaH))$sigmaH)
# Value of sigmaH to replace 'Inf' with for plotting
infinite_skew <- 10^2.35
# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^2.7

# Define sigmaH tick breaks and labels
sigmaH_breaks <- c(10^c(seq(-1, 2, by = 1)), 10^2.3125, 10^2.5625)
sigmaH_labels <- c(paste(c(10^c(seq(-1, 2, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$"))

CTmin_df <- data.CT %>%
  select(sigmaH, KH, Model, system_ID, variable, median, system_label) %>% 
  pivot_wider(names_from = variable, values_from = median) %>% 
  # If CTwidth is essentially zero, set CTmin to Inf indicating R0 < 1
  mutate(CTmin = if_else(CTwidth < eps, Inf, CTmin)) %>%
  mutate(sigmaH_proxy = sigmaH) %>%
  # Arrange along the plotting variables
  arrange(system_ID, KH, sigmaH_proxy, CTmin) %>%
  ungroup() %>%
  # Assign a value for cases where R0<1 for all temperatures
  mutate(CTmin = ifelse(is.finite(CTmin), CTmin, 100))

CTmin_df <- inf_skew_func(CTmin_df, infinite_skew, infinite_divide, 8)

maxCTmin <- ceiling(max(filter(CTmin_df, CTmin<100)$CTmin))

CTmin_breaks <- c(seq(14, 35, by = 2), 101)

CTmin_heat_plots <- CTmin_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = width of parasite thermal median_CTwidth
  ggplot(aes(x = KH, y = sigmaH_proxy, z = CTmin)) +
  # CTmin for FINITE sigmaH:
  geom_contour_filled(
    data = filter(
      CTmin_df,
      sigmaH_proxy < 10^2.2
    ),
    breaks = CTmin_breaks
  ) +
  # CTmin for INFINITE sigmaH:
  geom_contour_filled(
    data = filter(
      CTmin_df,
      sigmaH_proxy > 10^2.4,
      sigmaH_proxy < infinite_divide
    ),
    breaks = CTmin_breaks
  ) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # fill:
  scale_fill_manual(
    name = "Critical thermal minimum (°C)",
    values = c(viridis(9), "grey", "grey"),
    labels = ~ ifelse(.x < maxCTmin, .x, "n/a")
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top",
    title.hjust = 0.5,
    barwidth = 12,
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(10) +
  theme(
    legend.box = "horizontal",
    legend.position = "bottom",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(CTmin_heat_plots)
```

```{r fig-S5_CTmax, dev = c('pdf','svg', 'png'), dev="cairo_pdf", message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmax} The critical thermal maximum for parasite population persistence as a function of vertebrate host population density and biting tolerance. Grey areas indicate combinations of vertebrate host population density and biting tolerance in which the parasite population is expected to not persist at any temperature. In the region where vertebrate host population density and biting tolerance are both less than 10, critical thermal minima and maxima are very similar (see Figure 6 in the main text). Shown here are the median values of the critical thermal maximum with respect to mosquito trait TPC hyperparameter posterior distributions. Both vertebrate host population density and biting tolerance are varied on a $\\log_{10}$ scale with a break in biting tolerance values to indicate when biting tolerance is unlimited. '}
#   x    = biting tolerance (with a point at infinity)
#   y    = vertebrate host population density
# colour = parasite critical thermal maximum (CTmax)
# Facets = systems

# add many proxy sigmaH points at infinity to make the values easier to see there
max_sigmaH <- max(filter(data.CT, is.finite(sigmaH))$sigmaH)
# Value of sigmaH to replace 'Inf' with for plotting
infinite_skew <- 10^2.35
# Used to create a gap dividing finite and infinite sigmaH
infinite_divide <- 10^2.7

# Define sigmaH tick breaks and labels
sigmaH_breaks <- c(10^c(seq(-1, 2, by = 1)), 10^2.3125, 10^2.5625)
sigmaH_labels <- c(paste(c(10^c(seq(-1, 2, by = 1)))), TeX("$\\ldots$"), TeX("$\\infty$"))

CTmax_df <- data.CT %>%
  select(sigmaH, KH, Model, system_ID, variable, median, system_label) %>% 
  pivot_wider(names_from = variable, values_from = median) %>% 
  # If CTwidth is essentially zero, set CTmax to -Inf indicating R0 < 1
  mutate(CTmax = if_else(CTwidth < eps, Inf, CTmax)) %>%
  mutate(sigmaH_proxy = sigmaH) %>%
  # Arrange along the plotting variables
  arrange(system_ID, KH, sigmaH_proxy, CTmax) %>%
  ungroup() %>%
  # Assign a value for cases where R0<1 for all temperatures
  mutate(CTmax = ifelse(is.finite(CTmax), CTmax, -100))

CTmax_df <- inf_skew_func(CTmax_df, infinite_skew, infinite_divide, 8)

minCTmax <- floor(min(filter(CTmax_df, CTmax>0)$CTmax))

CTmax_breaks <- c(-101, seq(21, 35, by = 2))

CTmax_heat_plots <- CTmax_df %>%
  ## Set up plot ##
  # x = biting tolerance (with a point at infinity),
  # y = vertebrate host population density,
  # color = width of parasite thermal median_CTwidth
  ggplot(aes(x = KH, y = sigmaH_proxy, z = CTmax)) +
  # CTmin for FINITE sigmaH:
  geom_contour_filled(
    data = filter(
      CTmax_df,
      sigmaH_proxy < 10^2.2
    ),
    breaks = CTmax_breaks
  ) +
  # CTmin for INFINITE sigmaH:
  geom_contour_filled(
    data = filter(
      CTmax_df,
      sigmaH_proxy > 10^2.4,
      sigmaH_proxy < infinite_divide
    ),
    breaks = CTmax_breaks
  ) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E4),
    breaks = 10^seq(-1, 4, 1),
    labels = TeX(c("$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: log10-scale y axis, with no buffer space
  scale_y_log10(
    name = TeX("Biting tolerance (bites per host per day)"),
    expand = c(0, 0),
    breaks = sigmaH_breaks,
    labels = sigmaH_labels
  ) +
  # fill:
  scale_fill_manual(
    name = "Critical thermal maximum (°C)",
    values = c("grey", viridis(9)),
    labels = ~ ifelse(.x < minCTmax - 1, "n/a", .x)
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(fill = guide_coloursteps(
    title.position = "top",
    title.hjust = 0.5,
    barwidth = 12,
    show.limits = TRUE
  )) +
  # theme options:
  theme_minimal(10) +
  theme(
    legend.box = "horizontal",
    legend.position = "bottom",
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.direction = "horizontal",
    legend.justification = "left",
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

# Plot
shift_legend(CTmax_heat_plots)
```



```{r fig-S6_CT_Range, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_Range} The critical thermal minimum ($\\textrm{CT}_{\\min}$, blue curves) and maximum ($\\textrm{CT}_{\\max}$, red curves) for parasite population persistence depend on vertebrate host availability, even when vertebrate hosts tolerate any level of mosquito biting (dotted curves). Transmission is sustained ($\\mathcal{R}_0$>1) in the regions enclosed by the red and blue curves. $\\textrm{CT}_{\\min}$ is a convex function of vertebrate host population density while $\\textrm{CT}_{\\max}$ is concave. The points where the red and blue curves touch indicate thresholds of vertebrate host population density beyond which parasite population persistence is no longer possible at any temperature (i.e. $\\mathcal{R}_0$(T)<1) (see Figure 6 in the main text). Shown here are the median values of the critical thermal minimum, maximum, and mosquito thermal tolerance niche with respect to mosquito trait TPC hyperparameter posterior distributions. Both vertebrate host population density and biting tolerance are varied on a $\\log_{10}$ scale with a break in biting tolerance values to indicate when biting tolerance is unlimited. All remaining parameters are given in Table 1 and Figure 2.'}
# x-axis = vertebrate host population density
# y-axis = Temperature
# linetype = biting tolerance
# colour = CT_min (blue), CT_max (red)

CTRange_df <- data.CT %>%
  # Arrange along the plotting variables
  select(system_label, sigmaH, KH, variable, value = median) %>%
  # Choose a few sigmaH values to plot, including Inf
  filter(sigmaH %in% c(1, 10, 100, Inf)) %>%
  filter(KH %in% unique(KH)[seq(1, length(unique(KH)), length.out = 101)]) %>%
  pivot_wider(
    id_cols = c("system_label", "sigmaH", "KH"),
    names_from = variable, values_from = value
  ) %>%
  group_by(system_label, KH, sigmaH) %>%
  mutate(CTwidth = max(CTmax - CTmin, 0)) %>%
  filter(CTwidth > 0.05) %>%
  # Arrange along the plotting variables
  arrange(system_label, KH, sigmaH, CTmax, CTmin) %>%
  ungroup() %>%
  melt(id = c("system_label", "KH", "sigmaH")) %>%
  arrange(KH, sigmaH)

CTRange_plots <- CTRange_df %>%
  ## Set up plot ##
  # x-axis = population density, y-axis = temperature,
  # color = thermal extrema, linetype = sigmaH
  ggplot(
    aes(x = KH, y = value, linetype = as.factor(sigmaH), color = variable)
  ) +
  # Mosquito thermal tolerance range lines
  geom_hline(
    data = MosqThermRange_df,
    aes(yintercept = CTmin_V0, colour = "VTTR"),
    lwd = 1.275
  ) +
  geom_hline(
    data = MosqThermRange_df,
    aes(yintercept = CTmax_V0, colour = "VTTR"),
    lwd = 1.275
  ) +
  # Curves showing CTmin and CTmax
  geom_line(
    data = filter(CTRange_df, variable == "CTmin"),
    lwd = 1
  ) +
  geom_line(
    data = filter(CTRange_df, variable == "CTmax"),
    lwd = 1
  ) +
  # x-axis: log10-scale with no buffer space
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(1E-2, 1E5),
    breaks = 10^seq(-1, 4),
    labels = TeX(c("$0.1$", "$1$", "$10$", "$100$", "$10^3$", "$10^4$"))
  ) +
  # y-axis: small buffer space
  scale_y_continuous(
    name = expression("Temperature "(degree * C)),
    expand = c(0.05, 0.05),
    limits = c(min(MosqThermRange_df$CTmin_V0), max(MosqThermRange_df$CTmax_V0)),
    breaks = seq(floor(range(CTRange_df$value, na.rm = TRUE)[1]),
                 floor(range(CTRange_df$value, na.rm = TRUE)[2]),
                 by = 2
    )
  ) +
  # linetype:
  scale_linetype_manual(
    name = "Vertebrate host biting tolerance\n(bites per host per day)",
    values = c("solid", "dashed", "longdash", "dotted"),
    breaks = c(1, 10, 100, Inf),
    labels = unname(c("1 (Chitnis)", "10 (Chitnis)", "100 (Chitnis)", TeX("$\\infty$ (Ross-Macdonald)")))
  ) +
  # color:
  scale_colour_manual(
    name = "Thermal extrema",
    breaks = c("CTmax", "CTmin", "VTTR"),
    labels = c("Critical maximum", "Critical minimum", "Mosquito population\nthermal niche"),
    values = c("red", "blue", "grey"),
    guide = guide_legend(keyheight = unit(40, "cm"))
  ) +
  # faceting:
  facet_wrap(~system_label, scales = "free", nrow = 2, labeller = labeller()) +
  # legend:
  guides(
    color = guide_legend(override.aes = list(size = 4), order = 1),
    linetype = guide_legend(keywidth = 4, order = 2),
  ) +
  # theme options:
  theme_minimal_hgrid(10) +
  theme(
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0
    )
  )

# Plot
shift_legend(CTRange_plots)
```


```{r table-2_Toptdiffbound, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Toptdiffbound} Calculating how large the difference between the Ross-Macdonald and Chitnis Topt estimates can be.'}
# Estimating the difference between Topt and Topt_RM numerically using our previous data
Toptdiff_CCH <- data.Topt %>%
  ungroup() %>%
  select(system_ID, sigmaH, KH, median) %>%
  rename(Topt = median) %>%
  filter(is.finite(sigmaH)) %>%
  distinct()

Toptdiff_RM <- data.Topt %>%
  ungroup() %>%
  filter(is.infinite(sigmaH)) %>%
  select(system_ID, KH, median) %>%
  rename(Topt_RM = median) %>%
  distinct()

Toptdiff_df <- left_join(Toptdiff_CCH, Toptdiff_RM) %>%
  mutate(Toptdiff = Topt_RM - Topt) %>%
  mutate(absToptdiff = abs(Toptdiff)) %>%
  mutate(propToptdiff = (Topt_RM - Topt) / Topt_RM) %>%
  mutate(sigmaHKH = sigmaH * KH) %>%
  group_by(system_ID) %>%
  filter(absToptdiff == max(absToptdiff)) %>%
  select(-sigmaH, -KH, -sigmaHKH, -absToptdiff) %>%
  distinct()


# Calculating Topt0 using the "simplified" equation
Topt0_df <- median.Vec %>%
  filter(V0 > 1) %>%
  mutate(muV = 1 / (lf + eps)) %>%
  mutate(P_EIP = exp(-muV / etaV)) %>%
  mutate(proxy_0 = lf * betaV * P_EIP / (KL * rhoL * (lf - 1 / (sigmaV_f * deltaL)))) %>%
  select(system_ID, Temperature, proxy_0) %>%
  group_by(system_ID)

Topt0_base_estimates <- Topt0_df %>%
  group_by(system_ID) %>%
  # Calculate Topt_0
  filter(proxy_0 == proxy_0[which.max(proxy_0)]) %>%
  rename(Topt_0 = Temperature)

# Calculating Topt0 using the "simplified" equation
ToptRM_df <- median.Vec %>%
  mutate(muV = 1 / (lf + eps)) %>%
  mutate(P_EIP = exp(-muV / etaV)) %>%
  mutate(proxy_RM = sigmaV^2 * V0 * betaV * P_EIP / muV) %>%
  select(system_ID, Temperature, proxy_RM) %>%
  group_by(system_ID)

ToptRM_base_estimates <- data.Topt %>%
  group_by(system_ID) %>%
  filter(is.infinite(sigmaH)) %>%
  select(system_ID, median) %>%
  rename(Topt_RM = median) %>%
  distinct()

Topt_estimates_median <- left_join(ToptRM_base_estimates, Topt0_base_estimates) %>%
  select(system_ID, Topt_RM, Topt_0) %>%
  mutate(Topt_diff = Topt_RM - Topt_0) %>%
  mutate(prop_Topt_diff = abs(Topt_diff) / Topt_RM) %>% 
  arrange(system_ID)
```

```{r fig-S7_CT_distributions, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CT_dists} The distributions of the critical thermal minimum and maximum and thermal optimum vary across transmission systems and levels of vertebrate host availability. Distributions for the limited biting tolerance case (solid lines) and unlimited biting tolerance case (dashed lines) are shown above and below the vertebrate host population density levels, respectively. As vertebrate host population density is increased, the distributions become approximately equal, with the critical thermal minimum and maximum converging to each other at sufficiently high population densities. The \\textit{An. gambiae} and \\textit{P. falciparum} system shows the most drastic differences between the limited and unlimited biting tolerance cases at low vertebrate host population density levels. Vertebrate host population density is varied on a $\\log_{10}$ scale. '}
# half-violin plots
plot.densities_violin_inline <- ggplot() +
  # CT min
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Critical thermal minimum",
      sigmaH == 100
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "CTmin"),
    lwd = 0.75
  ) +
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Critical thermal minimum",
      sigmaH == Inf
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "CTmin"),
    lwd = 0.75,
    flip = TRUE
  ) +
  # CT max
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Critical thermal maximum",
      sigmaH == 100
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "CTmax"),
    lwd = 0.75
  ) +
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Critical thermal maximum",
      sigmaH == Inf
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "CTmax"),
    lwd = 0.75,
    flip = TRUE
  ) +
  # Thermal optima
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Thermal optimum",
      sigmaH == 100
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "Topt"),
    lwd = 0.75
  ) +
  geom_violinhalf(
    data = filter(
      all.density.df, variable == "Thermal optimum",
      sigmaH == Inf
    ),
    aes(y = value, x = KH_factor, linetype = sigmaH, fill = "Topt"),
    lwd = 0.75,
    flip = TRUE
  ) +
  scale_x_discrete(
    name = "Vertebrate host population density (ind/ha)"
  ) +
  scale_y_continuous(
    name = "Temperature (°C)",
    expand = c(0, 0)
  ) +
  scale_linetype(
    name = "Biting tolerance\n(bites per host per day)"
  ) +
  scale_fill_discrete(
    name = "",
    breaks = c("CTmin", "Topt", "CTmax"),
    labels = c("Critical thermal minimum", "Thermal optimum", "Critical thermal maximum")
  ) +
  facet_wrap(~system_label, labeller = labeller(), scales = "free_x") +
  theme_minimal_grid(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  ) +
  coord_flip()
shift_legend(plot.densities_violin_inline)
```

```{r fig-S8_R0_sensitivity, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:dR0dvar_unc} The local sensitivity of $\\mathcal{R}_0$ to mosquito traits across temperatures for two values of $\\sigma_H$ and $K_H$. Generally, $\\mathcal{R}_0$ is most sensitive to biting frequency, the probability of surviving the extrinsic incubation period, and vector competence. Shown here are the median values of the derivative of $\\mathcal{R}_0$ with respect to each focal mosquito trait across the mosquito trait TPC hyperparameter posterior distributions. Sensitivity values are shown on a logarithmic scale with solid lines indicating positive values and dotted lines indicating negative. Temperatures are restricted to those at which the median of $\\mathcal{R}_0$ is positive for the given system. '}
KH_vals = c(1,100)

data.dR0dT <- data.dR0dvar %>%
  filter((KH %in% KH_vals & sigmaH == 10) | (KH == 100 & is.infinite(sigmaH)))

temp_lims <- select(data.R0, system_ID, system_label, Temperature, Model, sigmaH, KH, median_R0 = median) %>%
  filter(KH %in% KH_vals & sigmaH %in% c(100, Inf)) %>%
  filter(!is.na(median_R0), median_R0 > eps) %>%
  group_by(system_ID) %>% 
  summarise(min_Temp = min(Temperature),
            max_Temp = max(Temperature))


val_lims <- tibble(sigmaH = unique(data.dR0dT$sigmaH), 
                   min_median = c(-90, -0.05), 
                   max_median = c(5, 0.5))


dR0dk.df <- data.dR0dT %>% 
  filter(
    KH %in% KH_vals,
    sigmaH %in% unique(data.dR0dT$sigmaH)
  ) %>%
  right_join(select(data.R0, system_ID, system_label, Temperature, Model, sigmaH, KH, median_R0 = median) %>%
               filter(KH %in% KH_vals & sigmaH %in% unique(data.dR0dT$sigmaH))) %>%
  # Restrict to relevant temperatures (i.e. where V0 and R0 > 0)
  right_join(temp_lims) %>% 
  group_by(system_ID) %>% 
  filter(Temperature > min_Temp, Temperature < max_Temp) %>% 
  filter(!is.na(median)) %>% 
  ungroup() %>% 
  # Restrict plotted values (so all plots are visible)
  right_join(val_lims) %>% 
  group_by(sigmaH) %>% 
  # filter(median > min_median, median < max_median) %>% 
  ungroup() %>% 
  # filter(median_R0 > 0) %>%
  mutate(abs_median = abs(median)) %>%
  # Normalize values to better tell which is most important
  mutate(sign_median = sign(median)) %>%
  group_by(system_ID, sigmaH, KH) %>%
  mutate(norm_median = ifelse(sign_median>0,
                              abs_median / max(median, na.rm = TRUE),
                              abs_median / min(median, na.rm = TRUE))
         ) %>%
  filter(sign_median != 0, !is.na(sign_median)) %>%
  arrange(sign_median) %>%
  arrange(Temperature)


# NB: in order to produce an R0 TPC, "overall" derivative should go from positive to negative
plot.dR0dk <- dR0dk.df %>%
  # filter(focal_var %in% c("Overall")) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = Temperature, y = median, color = focal_var, 
             # linetype = (as.factor(sign_median))
  )) +
  geom_line(lwd = 0.5) +
  geom_hline(yintercept = 0, lwd = 0.25) +
  scale_color_manual(
    name = "Focal trait:",
    values = rev(c(c4a("misc.okabe", 7), "black"))
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    name = unname(TeX("Contribution to local temperature sensitivity of $\\,R_0$")),

    expand = c(0, 0)
  ) +
  coord_capped_cart(ylim = c(-1,1)) +
  facet_grid(
    rows = vars(KH, sigmaH),
    cols = vars(system_label),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed),
      KH = as_labeller(appender_KH, default = label_parsed)
    ),
    scales = "free"
  ) +
  guides(linetype = guide_legend(
    title.position = "left",
    title.vjust = 0.5,
    direction = "vertical"
  )) +
  theme_minimal_hgrid(10) +
  theme(
    panel.spacing = unit(1, "lines"),
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    legend.position = "bottom",
    legend.justification = 0.5,
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )


plot.dR0dk
```


```{r fig-S9_ddTR0_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:ddTR0_unc} The uncertainty in the sensitivity of $\\mathcal{R}_0$ with respect to temperature.'}
## Plot R0 uncertainty
Temp_range_for_plot <- ddTR0.HPD %>%
  ungroup() %>%
  dplyr::filter(HPD_width > eps) %>%
  select(Temperature) %>%
  range()

plot.ddTR0.rel.sens <- ddTR0.HPD %>%
  filter(KH %in% c(1) & sigmaH %in% c(100, Inf)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty across parameters
  group_by(system_ID, sigmaH, KH, Temperature) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total uncertainty
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  arrange(sens_rel) %>%
  arrange(focal_var) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = Temperature, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $dR_0 / dT$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(sigmaH),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed)
    ),
    scales = "free"
  ) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.position = "bottom",
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )

plot.ddTR0.rel.sens
```



```{r fig-S10_Topt_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_unc} The uncertainty of $T_{\\textrm{opt}}$ to mosquito traits across vertebrate host population densities as measured by the change in the 95\\% highest posterior density interval width when $\\sigma_H$ is 100 bites per vertebrate host per day. At high levels of vertebrate host population density, the effect of vertebrate host traits diminishes and the relative sensitivities of $T_{\\textrm{opt}}$ to mosquito traits stabilize. Generally, adult lifespan is an influential parameter and, to lesser extents, vector competence and the probability of surviving the extrinsic incubation period (EIP). Eggs per female per day tends to be most important when vertebrate host population density is low, though this not the case for (e) \\textit{Cx. quinquefasciatus} and WNV.Immature development rate and the probability of immature survival are never very influential parameters. Vertebrate host population density is varied on a $\\log_{10}$ scale. '}
plot.Topt.rel.sens <- Topt.HPD %>%
  ungroup() %>%
  distinct() %>%
  filter(sigmaH == 100) %>%
  filter(!is.na(HPD_width)) %>%
  pathosystem_labeller() %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total uncertainty
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    limits = c(0.05, 1E3),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $T_{opt}$ HPD width"))
  ) +
  facet_wrap(~system_label) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.Topt.rel.sens)
```

```{r fig-S10_2_dToptdKH_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:Topt_unc2} The uncertainty in the sensitivity of the thermal optimum to host availability as a function of vertebrate host population density when $\\sigma_H = 100$.'}
dToptdKH.HPD <- dToptdKH.HPD %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total uncertainty
  mutate(sens_rel = rel_HPD_width / sens_total)

plot.dToptdKH.rel.sens <- dToptdKH.HPD %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $ dT_{opt}/dK_H$ HPD width"))
  ) +
  facet_wrap(~system_label) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 10,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    )
  )
shift_legend(plot.dToptdKH.rel.sens)
```

```{r fig-S11_CTmin_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmin_unc} The uncertainty of $\\textrm{CT}_{\\min}$ to mosquito traits across vertebrate host population densities as measured by the change in the 95\\% highest posterior density interval width for two values of $\\sigma_H$. Sensitivities are only plotted when $\\textrm{CT}_{\\min}$ exists for the given value of vertebrate host population density. Generally, eggs per female per day and the probability of surviving the EIP are the most influential parameters. $\\textrm{CT}_{\\min}$ is sensitive to vector competence across the full range of vertebrate host population densities for systems (b) and (e) but, in systems (a), (c), and (d), only when population density is high. Immature development rate and the probability of immature survival are not very influential parameters and $\\textrm{CT}_{\\min}$ is only sensitive to biting frequency in the case of system (e) when vertebrate host population density is high. Vertebrate host population density is varied on a $\\log_{10}$ scale. '}
CTmin_df <- CT.HPD %>%
  filter(variable == "CTmin") %>%
  filter(sigmaH %in% c(100, Inf)) %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total uncertainty
  mutate(sens_rel = rel_HPD_width / sens_total) # %>%

# Make a stacked plot, colored by parameter
plot.CTmin.rel.sens <- CTmin_df %>%
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $CT_{min}$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(sigmaH),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed)
    )
  ) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.position = "bottom",
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 8,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    ),
    panel.spacing.x = unit(2, "lines")
  )
plot.CTmin.rel.sens
```

```{r fig-S12_CTmax_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTmax_unc} The uncertainty of $\\textrm{CT}_{\\max}$ to mosquito traits across vertebrate host population densities as measured by the change in the 95\\% highest posterior density interval width for two values of $\\sigma_H$. Sensitivities are only plotted when $\\textrm{CT}_{\\max}$ exists for the given value of vertebrate host population density. Generally, adult mosquito life span is the most influential parameter. At low vertebrate host population densities, $\\textrm{CT}_{\\max}$ is sensitive to eggs per female per day in systems (c) and (e). $\\textrm{CT}_{\\max}$ is only sensitive to biting frequency in the case of system (e) when vertebrate host population density is high. The influence of other parameters increases at high levels of vertebrate host population density. Vertebrate host population density is varied on a $\\log_{10}$ scale. '}
plot.CTmax.rel.sens <- CT.HPD %>%
  filter(variable == "CTmax") %>%
  filter(sigmaH %in% c(100, Inf)) %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total uncertainty
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $CT_{max}$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(sigmaH),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(appender_sigmaH, default = label_parsed)
    )
  ) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.position = "bottom",
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 8,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    ),
    panel.spacing.x = unit(2, "lines")
  )
plot.CTmax.rel.sens
```




```{r fig-S13_CTwidth_uncertainty, dev = c('pdf','svg', 'png'), message=FALSE, out.width='100%', fig.width=9, fig.height=6, fig.align='center', fig.cap='\\label{fig:CTwidth_unc}  The uncertainty of $\\textrm{CT}_{\\textrm{width}}$ to mosquito traits across vertebrate host population densities as measured by the change in the 95\\% highest posterior density interval width for two values of $\\sigma_H$. Sensitivities are only plotted when $\\textrm{CT}_{\\textrm{width}}$exists for the given value of vertebrate host population density. Generally, adult mosquito life span, eggs per female per day, and the probability of surviving the EIP are the most influential parameters, though $\\textrm{CT}_{\\textrm{width}}$ is not sensitive the probability of surviving the EIP in system (d). $\\textrm{CT}_{\\textrm{width}}$ is only sensitive to biting frequency in the case of system (e) when vertebrate host population density is high. Vertebrate host population density is varied on a $\\log_{10}$ scale. '}
plot.CTwidth.rel.sens <- CT.HPD %>%
  filter(variable == "CTwidth") %>%
  filter(sigmaH %in% c(100, Inf)) %>%
  filter(!is.na(rel_HPD_width)) %>%
  # For each KH value, sum up all uncertainty values to get total uncertainty
  group_by(system_ID, sigmaH, KH) %>%
  mutate(sens_total = sum(rel_HPD_width)) %>%
  # Divide each uncertainty value by the total sensitiviWty
  mutate(sens_rel = rel_HPD_width / sens_total) %>%
  # Make a stacked plot, colored by parameter
  ggplot(aes(x = KH, y = sens_rel, fill = focal_var)) +
  geom_area() +
  scale_fill_manual(
    name = "Focal trait:",
    values = rev(c4a("misc.okabe", 7))
  ) +
  scale_x_log10(
    name = TeX("Vertebrate host population density (ind/ha)"),
    expand = c(0, 0),
    breaks = 10^seq(-2, 4, 1),
    labels = TeX(c("$0.01$", "$0.1$", "$1$", "$10", "$100$", "$10^3$", "$10^4$"))
  ) +
  scale_y_continuous(
    name = unname(TeX("Relative contribution to $CT_{width}$ HPD width"))
  ) +
  facet_grid(
    cols = vars(system_label),
    rows = vars(sigmaH),
    labeller = labeller(
      system_label = sens_labels,
      sigmaH = as_labeller(
        appender_sigmaH,
        default = label_parsed
      )
    )
  ) +
  theme_minimal(10) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.position = "bottom",
    axis.title.x = element_text(hjust = 0.5),
    strip.text.x = ggtext::element_markdown(
      size = 8,
      hjust = 0,
      padding = margin(0, 0, 0, 0),
      margin = margin(1, 1, 1, 1)
    ),
    panel.spacing.x = unit(2, "lines")
  )
plot.CTwidth.rel.sens
```
